name: gauge_progress
description: A customizable semi-circular gauge progress widget for Flutter with adjustable colors, stroke widths, and size.
version: 1.0.0

homepage: https://github.com/amityamsi/gauge_progress
repository: https://github.com/amityamsi/gauge_progress
issue_tracker: https://github.com/amityamsi/gauge_progress/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

topics:
  - gauge
  - progress
  - chart
  - custom-painter
  - dashboard
screenshots:
  - description: Gauge Progress Demo
    path: src/app.gif
